name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.8.0+1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  flutter_mana: ^1.0.0-beta.7
  flutter_mana_kits: ^1.0.0-beta.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

