name: example
description: "Flutter Mana Example"
publish_to: 'none'
version: 1.3.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  logger: ^2.6.2
  shared_preferences: ^2.5.3
  flutter_mana: any
  flutter_mana_kits: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/test.jpeg

