name: flutter_mana_kits
description: "Flutter Mana Kits"
version: 1.0.0-beta.8
homepage: https://github.com/lhlyu/flutter_mana/tree/master/kits

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mana: ^1.0.0-beta.14
  dio: ^5.8.0+1
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  device_info_plus: ^11.5.0
  syntax_highlight: ^0.4.0
  package_info_plus: ^8.3.0
  vm_service: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
