name: flutter_mana_kits
description: "Flutter Mana Kits"
version: 1.3.1
homepage: https://github.com/lhlyu/flutter_mana/tree/master/packages/kits
repository: https://github.com/lhlyu/flutter_mana
documentation: https://github.com/lhlyu/flutter_mana
issue_tracker: https://github.com/lhlyu/flutter_mana/issues
topics: [ debug, in-app-debug, diagnostics, plugin ]

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"
resolution: workspace 

dependencies:
  flutter:
    sdk: flutter

  flutter_mana: ^1.3.0
  dio: ^5.9.0
  logger: ^2.6.2
  shared_preferences: ^2.5.3
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  vm_service: ^15.0.2
  string_scanner: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
