name: Build and Release Flutter APK

on:
  release:
    types: [created]

jobs:
  build-apk:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get
        working-directory: ./example

      - name: Build APK
        run: flutter build apk --debug
        working-directory: ./example

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./example/build/app/outputs/flutter-apk/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}